## code to prepare indicator join tables that rename indicators and provide indicator features

data_em_imer_var_map <-
tibble::tribble(
                ~indicator,                                    ~indicator_new,
               "TX_NEWTot",                                          "remove",
                "TX_NEWBF",                          "TX_NEW...Breastfeeding",
                 "TX_N_M1",                                     "TX_NEW.M.<1",
                 "TX_N_M2",                                    "TX_NEW.M.1_4",
                 "TX_N_M3",                                    "TX_NEW.M.5_9",
                 "TX_N_M4",                                  "TX_NEW.M.10_14",
                 "TX_N_M5",                                  "TX_NEW.M.15_19",
                 "TX_N_M6",                                  "TX_NEW.M.20_24",
                 "TX_N_M7",                                  "TX_NEW.M.25_29",
                 "TX_N_M8",                                  "TX_NEW.M.30_34",
                 "TX_N_M9",                                  "TX_NEW.M.35_39",
                "TX_N_M10",                                  "TX_NEW.M.40_44",
                "TX_N_M11",                                  "TX_NEW.M.45_49",
                "TX_N_M12",                                  "TX_NEW.M.50_54",
                "TX_N_M13",                                  "TX_NEW.M.55_59",
                "TX_N_M14",                                  "TX_NEW.M.60_64",
                "TX_N_M15",                                    "TX_NEW.M.65+",
                "TX_N_M16",                                "TX_NEW.M.unknown",
                "TX_N_MST",                                          "remove",
                 "TX_N_F1",                                     "TX_NEW.F.<1",
                 "TX_N_F2",                                    "TX_NEW.F.1_4",
                 "TX_N_F3",                                    "TX_NEW.F.5_9",
                 "TX_N_F4",                                  "TX_NEW.F.10_14",
                 "TX_N_F5",                                  "TX_NEW.F.15_19",
                 "TX_N_F6",                                  "TX_NEW.F.20_24",
                 "TX_N_F7",                                  "TX_NEW.F.25_29",
                 "TX_N_F8",                                  "TX_NEW.F.30_34",
                 "TX_N_F9",                                  "TX_NEW.F.35_39",
                "TX_N_F10",                                  "TX_NEW.F.40_44",
                "TX_N_F11",                                  "TX_NEW.F.45_49",
                "TX_N_F12",                                  "TX_NEW.F.50_54",
                "TX_N_F13",                                  "TX_NEW.F.55_59",
                "TX_N_F14",                                  "TX_NEW.F.60_64",
                "TX_N_F15",                                    "TX_NEW.F.65+",
                "TX_N_F16",                                "TX_NEW.F.unknown",
                "TX_N_FST",                                          "remove",
               "TX_N_PWID",                                   "TX_NEW...PWID",
                "TX_N_MSM",                                    "TX_NEW...MSM",
                "TX_N_FSW",                                    "TX_NEW...FSW",
               "TX_N_PPCS",                                   "TX_NEW...PPCS",
              "TX_N_Check",                                          "remove",
               "TX_CURTot",                                          "remove",
                 "TX_C_M1",                                    "TX_CURR.M.<1",
                 "TX_C_M2",                                   "TX_CURR.M.1_4",
                 "TX_C_M3",                                   "TX_CURR.M.5_9",
                 "TX_C_M4",                                 "TX_CURR.M.10_14",
                 "TX_C_M5",                                 "TX_CURR.M.15_19",
                 "TX_C_M6",                                 "TX_CURR.M.20_24",
                 "TX_C_M7",                                 "TX_CURR.M.25_29",
                 "TX_C_M8",                                 "TX_CURR.M.30_34",
                 "TX_C_M9",                                 "TX_CURR.M.35_39",
                "TX_C_M10",                                 "TX_CURR.M.40_44",
                "TX_C_M11",                                 "TX_CURR.M.45_49",
               "TX_C_M121",                                 "TX_CURR.M.50_54",
               "TX_C_M124",                                 "TX_CURR.M.55_59",
               "TX_C_M123",                                 "TX_CURR.M.60_64",
               "TX_C_M122",                                   "TX_CURR.M.65+",
                "TX_C_M13",                               "TX_CURR.M.unknown",
                "TX_C_M14",                                          "remove",
                 "TX_C_F1",                                    "TX_CURR.F.<1",
                 "TX_C_F2",                                   "TX_CURR.F.1_4",
                 "TX_C_F3",                                   "TX_CURR.F.5_9",
                 "TX_C_F4",                                 "TX_CURR.F.10_14",
                 "TX_C_F5",                                 "TX_CURR.F.15_19",
                 "TX_C_F6",                                 "TX_CURR.F.20_24",
                 "TX_C_F7",                                 "TX_CURR.F.25_29",
                 "TX_C_F8",                                 "TX_CURR.F.30_34",
                 "TX_C_F9",                                 "TX_CURR.F.35_39",
                "TX_C_F10",                                 "TX_CURR.F.40_44",
                "TX_C_F11",                                 "TX_CURR.F.45_49",
               "TX_C_F121",                                 "TX_CURR.F.50_54",
               "TX_C_F124",                                 "TX_CURR.F.55_59",
               "TX_C_F123",                                 "TX_CURR.F.60_64",
               "TX_C_F122",                                   "TX_CURR.F.65+",
                "TX_C_F13",                               "TX_CURR.F.unknown",
                "TX_C_F14",                                          "remove",
               "TX_C_PWID",                                  "TX_CURR...PWID",
                "TX_C_MSM",                                   "TX_CURR...MSM",
                "TX_C_FSW",                                   "TX_CURR...FSW",
               "TX_C_PPCS",                                  "TX_CURR...PPCS",
          "TX_C_3Mo_D_Tot",                                          "remove",
       "TX_C_3Mo_D_M_Chil",                              "TX_MMD.M.<15..<3",
       "TX_C_3Mo_D_M_Adul",                              "TX_MMD.M.15+..<3",
        "TX_C_3Mo_D_M_Unk",                          "TX_MMD.M.unknown..<3",
       "TX_C_3Mo_D_F_Chil",                              "TX_MMD.F.<15..<3",
       "TX_C_3Mo_D_F_Adul",                              "TX_MMD.F.15+..<3",
        "TX_C_3Mo_D_F_Unk",                          "TX_MMD.F.unknown..<3",
        "TX_C_3_5Mo_D_Tot",                                          "remove",
     "TX_C_3_5Mo_D_M_Chil",                             "TX_MMD.M.<15..3-5",
     "TX_C_3_5Mo_D_M_Adul",                             "TX_MMD.M.15+..3-5",
      "TX_C_3_5Mo_D_M_Unk",                         "TX_MMD.M.unknown..3-5",
     "TX_C_3_5Mo_D_F_Chil",                             "TX_MMD.F.<15..3-5",
     "TX_C_3_5Mo_D_F_Adul",                             "TX_MMD.F.15+..3-5",
      "TX_C_3_5Mo_D_F_Unk",                         "TX_MMD.F.unknown..3-5",
          "TX_C_6Mo_D_Tot",                                          "remove",
       "TX_C_6Mo_D_M_Chil",                              "TX_MMD.M.<15..6+",
       "TX_C_6Mo_D_M_Adul",                              "TX_MMD.M.15+..6+",
        "TX_C_6Mo_D_M_Unk",                          "TX_MMD.M.unknown..6+",
       "TX_C_6Mo_D_F_Chil",                              "TX_MMD.F.<15..6+",
       "TX_C_6Mo_D_F_Adul",                              "TX_MMD.F.15+..6+",
        "TX_C_6Mo_D_F_Unk",                          "TX_MMD.F.unknown..6+",
              "TX_C_Check",                                          "remove",
               "IMER1_Tot",                                          "remove",
                "IMER1_PW",                          "IMER_1_D...Pregnant..D",
                "IMER1_BF",                     "IMER_1_D...Breastfeeding..D",
                "IMER1_14",               "IMER_1_D...Non-Pregnant Adults..D",
            "IMER1_Adults",                         "IMER_1_D...Pediatric..D",
               "IMER2_Tot",                                          "remove",
                "IMER2_PW",                          "IMER_1_N...Pregnant..N",
                "IMER2_BF",                     "IMER_1_N...Breastfeeding..N",
                "IMER2_14",               "IMER_1_N...Non-Pregnant Adults..N",
            "IMER2_Adults",                         "IMER_1_N...Pediatric..N",
              "IMER1_Tot2",                                          "remove",
               "IMER1B_PW",                         "IMER_1B_D...Pregnant..D",
               "IMER1B_BF",                    "IMER_1B_D...Breastfeeding..D",
               "IMER1B_14",              "IMER_1B_D...Non-Pregnant Adults..D",
           "IMER1B_Adults",                        "IMER_1B_D...Pediatric..D",
              "IMER2B_Tot",                                          "remove",
               "IMER2B_PW",                         "IMER_1B_N...Pregnant..N",
               "IMER2B_BF",                    "IMER_1B_N...Breastfeeding..N",
               "IMER2B_14",              "IMER_1B_N...Non-Pregnant Adults..N",
           "IMER2B_Adults",                        "IMER_1B_N...Pediatric..N",
               "I3_ER1_01",                                          "remove",
               "I3_ER1_02",                                          "remove",
               "I3_ER1_03",                                          "remove",
               "I3_ER1_04",                                          "remove",
               "I3_ER1_05",                                          "remove",
               "I3_ER1_06",                                          "remove",
       "I3_ER1_07_RetCalc",                                          "remove",
               "I3_ER1_08",              "ER_1_D...Pregnant..D.Initiated ART",
               "I3_ER1_09",                       "ER_1_N...Pregnant..N.LTFU",
               "I3_ER1_10",                   "ER_1_N...Pregnant..N.Retained",
               "I3_ER1_11",                       "ER_1_N...Pregnant..N.Died",
               "I3_ER1_12",            "ER_1_N...Pregnant..N.Transferred Out",
               "I3_ER1_13",                "ER_1_N...Pregnant..N.Stopped ART",
       "I3_ER1_14_RetCalc",                                          "remove",
               "I3_ER1_15",         "ER_1_D...Breastfeeding..D.Initiated ART",
               "I3_ER1_16",                  "ER_1_N...Breastfeeding..N.LTFU",
               "I3_ER1_17",              "ER_1_N...Breastfeeding..N.Retained",
               "I3_ER1_18",                  "ER_1_N...Breastfeeding..N.Died",
               "I3_ER1_19",       "ER_1_N...Breastfeeding..N.Transferred Out",
               "I3_ER1_20",           "ER_1_N...Breastfeeding..N.Stopped ART",
       "I3_ER1_21_RetCalc",                                          "remove",
               "I3_ER1_22",             "ER_1_D...Pediatric..D.Initiated ART",
               "I3_ER1_23",                      "ER_1_N...Pediatric..N.LTFU",
               "I3_ER1_24",                  "ER_1_N...Pediatric..N.Retained",
               "I3_ER1_25",                      "ER_1_N...Pediatric..N.Died",
               "I3_ER1_26",           "ER_1_N...Pediatric..N.Transferred Out",
               "I3_ER1_27",               "ER_1_N...Pediatric..N.Stopped ART",
       "I3_ER1_28_RetCalc",                                          "remove",
               "I3_ER1_29",   "ER_1_D...Non-Pregnant Adults..D.Initiated ART",
               "I3_ER1_30",            "ER_1_N...Non-Pregnant Adults..N.LTFU",
               "I3_ER1_31",        "ER_1_N...Non-Pregnant Adults..N.Retained",
               "I3_ER1_32",            "ER_1_N...Non-Pregnant Adults..N.Died",
               "I3_ER1_33", "ER_1_N...Non-Pregnant Adults..N.Transferred Out",
               "I3_ER1_34",     "ER_1_N...Non-Pregnant Adults..N.Stopped ART",
       "I3_ER1_35_RetCalc",                                          "remove",
               "I4_ER4_01",                                          "remove",
               "I4_ER4_02",                                          "remove",
               "I4_ER4_03",                                          "remove",
               "I4_ER4_04",                                          "remove",
               "I4_ER4_05",                                          "remove",
               "I4_ER4_06",                                          "remove",
               "I4_ER4_07",                                          "remove",
       "I4_ER4_08_RetCalc",                                          "remove",
               "I4_ER4_09",              "ER_4_D...Pregnant..D.Initiated ART",
               "I4_ER4_10",                  "ER_4_N...Pregnant..N.Defaulter",
               "I4_ER4_11",                   "ER_4_N...Pregnant..N.Retained",
               "I4_ER4_12",                       "ER_4_N...Pregnant..N.Died",
               "I4_ER4_13",                       "ER_4_N...Pregnant..N.LTFU",
               "I4_ER4_14",            "ER_4_N...Pregnant..N.Transferred Out",
               "I4_ER4_15",                "ER_4_N...Pregnant..N.Stopped ART",
       "I4_ER4_16_RetCalc",                                          "remove",
               "I4_ER4_17",         "ER_4_D...Breastfeeding..D.Initiated ART",
               "I4_ER4_18",             "ER_4_N...Breastfeeding..N.Defaulter",
               "I4_ER4_19",              "ER_4_N...Breastfeeding..N.Retained",
               "I4_ER4_20",                  "ER_4_N...Breastfeeding..N.Died",
               "I4_ER4_21",                  "ER_4_N...Breastfeeding..N.LTFU",
               "I4_ER4_22",       "ER_4_N...Breastfeeding..N.Transferred Out",
               "I4_ER4_23",           "ER_4_N...Breastfeeding..N.Stopped ART",
       "I4_ER4_24_RetCalc",                                          "remove",
               "I4_ER4_25",             "ER_4_D...Pediatric..D.Initiated ART",
               "I4_ER4_26",                 "ER_4_N...Pediatric..N.Defaulter",
               "I4_ER4_27",                  "ER_4_N...Pediatric..N.Retained",
               "I4_ER4_28",                      "ER_4_N...Pediatric..N.Died",
               "I4_ER4_29",                      "ER_4_N...Pediatric..N.LTFU",
               "I4_ER4_30",           "ER_4_N...Pediatric..N.Transferred Out",
               "I4_ER4_31",               "ER_4_N...Pediatric..N.Stopped ART",
       "I4_ER4_32_RetCalc",                                          "remove",
               "I4_ER4_33",   "ER_4_D...Non-Pregnant Adults..D.Initiated ART",
               "I4_ER4_34",       "ER_4_N...Non-Pregnant Adults..N.Defaulter",
               "I4_ER4_35",        "ER_4_N...Non-Pregnant Adults..N.Retained",
               "I4_ER4_36",            "ER_4_N...Non-Pregnant Adults..N.Died",
               "I4_ER4_37",            "ER_4_N...Non-Pregnant Adults..N.LTFU",
               "I4_ER4_38", "ER_4_N...Non-Pregnant Adults..N.Transferred Out",
               "I4_ER4_39",     "ER_4_N...Non-Pregnant Adults..N.Stopped ART",
       "I4_ER4_40_RetCalc",                                          "remove",
        "TXCURRMISAUTotal",                                          "remove",
      "TX_C_MISAU_PED_0.4",                       "TX_CURR_MISAU.unknown.0_4",
      "TX_C_MISAU_PED_5.9",                       "TX_CURR_MISAU.unknown.5_9",
  "TX_C_MISAU_PED_M_10.14",                           "TX_CURR_MISAU.M.10_14",
  "TX_C_MISAU_PED_F_10.14",                           "TX_CURR_MISAU.F.10_14",
  "TX_C_MISAU_PED_M_15.19",                           "TX_CURR_MISAU.M.15_19",
  "TX_C_MISAU_PED_F_15.19",                           "TX_CURR_MISAU.F.15_19",
     "TX_C_MISAU_AD_M_20p",                             "TX_CURR_MISAU.M.20+",
     "TX_C_MISAU_AD_F_20p",                             "TX_CURR_MISAU.F.20+"
  )
usethis::use_data(data_em_imer_var_map, overwrite = TRUE)

data_sdp_orgunituid_map <-
tibble::tribble(
       ~orgunituid,       ~recode,
     "TNxjWVnFcH3", "atj39UeK8N9",
     "MLWfwGSAExm", "Ay6W05BTgDV",
     "Eltn3fV50IH", "bRkKgVQ1bbn",
     "EOiaX9x1o8g", "D5BprGY8EIU",
     "j7R6NW899TU", "Dhku9zrZoJe",
     "ld9H4kG1Bnr", "EefeXxr8yDS",
     "yyR3ZgRyBzQ", "F8ZvmoAy2bh",
     "BdBJXnCZRJ5", "fJy2O3xh1fV",
     "ZZlLKqhLyve", "fJy2O3xh1fV",
     "imEg2imKHMv", "FNUYBvpbWaA",
     "c5OMOnQ8Yuf", "gUve5bZAut8",
     "ZKcg6E0YW40", "HcKIEHFgpDb",
     "eKkUVSMc9VE", "k6fqIh47UYc",
     "iqL4lrR62dI", "kyGz0JzX3Z0",
     "xiz4opVckuD", "nUanptGavqT",
     "A2WP9rKyeCd", "nx2J294i6hk",
     "bigmUwX7nZi", "oN0anW8xCpq",
     "MrzLUXqobYg", "oNDzB1D5as4",
     "Ld3DBzAtu2q", "PWXwPbUM2DB",
     "SnbIkc5HFdC", "qQ84fCTxdGh",
     "p1khrkzyj1C", "qU7z54bY9jA",
     "crU0qFcl39a", "siMZUtd2cJW",
     "e1ucJNfbCNo", "siMZUtd2cJW",
     "FMadYBJcUXZ", "siMZUtd2cJW",
     "MWbzgovlaB7", "siMZUtd2cJW",
     "ncwP2HaqFru", "siMZUtd2cJW",
     "siMZUtd2cJW", "siMZUtd2cJW",
     "ubKeGKFgG6p", "siMZUtd2cJW",
     "VTgqf9zaWJR", "siMZUtd2cJW",
     "wBH8Pu2Ho4Q", "siMZUtd2cJW",
  "srTB-HIVJGYtcK", "srTptJGYtcK",
     "IbTdghFlhMi", "XPhxWI0fDyq",
     "Y9W059tBM50", "yJ014QFEqru",
     "YDiTYO8iXlo", "zaeb1Zos2Mu"
  )

usethis::use_data(data_sdp_orgunituid_map, overwrite = TRUE)

