## code to prepare indicator join tables that rename indicators and provide indicator features

data_sisma_smi_cpn_map <-
  tibble::tribble(
                                                                             ~indicator,         ~indicator_new,    ~age,        ~disaggregate,
                                      "smi_cpn_gestantes_com_desnutricao_aguda_curadas",    "MG_NUT_DESNUT_CUR",      NA,                   NA,
                              "smi_cpn_gestantes_com_desnutricao_aguda_que_abandonaram",   "MG_NUT_DESNUT_ABND",      NA,                   NA,
                                                 "smi_cpn_inicio_de_profilaxia_com_inh",            "MG_TB_INH",      NA,                   NA,
                                        "smi_cpn_inicio_de_tratamento_para_tuberculose",             "MG_TB_TX",      NA,                   NA,
                                   "smi_cpn_mulheres_gravidas_que_iniciaram_ctz_coorte",           "MG_HIV_CTZ",      NA,         "Inicio CTZ",
                               "smi_cpn_mulheres_gravidas_que_receberam_desparasitante",       "MG_NUT_DESPARA",      NA,                   NA,
                                                 "smi_cpn_mulheres_gravidas_10_14_anos",          "MG_CON1_MES", "10-14",                   NA,
                                                 "smi_cpn_mulheres_gravidas_15_19_anos",          "MG_CON1_MES", "15-19",                   NA,
                                                 "smi_cpn_mulheres_gravidas_20_24_anos",          "MG_CON1_MES", "20-24",                   NA,
                                                    "smi_cpn_mulheres_gravidas_25_anos",          "MG_CON1_MES",   "25+",                   NA,
                                     "smi_cpn_mulheres_gravidas_hiv_positiva_a_entrada",        "MG_HIV_ESTADO",      NA, "Positivo a entrada",
              "smi_cpn_mulheres_gravidas_com_ganho_1_5_kg_mes_a_partir_do_2o_trimestre",    "MG_NUT_GANHO_2TRI",      NA,                   NA,
                    "smi_cpn_mulheres_gravidas_com_diagnostico_laboratorial_de_malaria",          "MG_MAL_DIAG",      NA,                   NA,
                        "smi_cpn_mulheres_gravidas_com_diagnostico_sindromico_para_its",          "MG_ITS_DIAG",      NA,                   NA,
      "smi_cpn_mulheres_gravidas_com_menos_de_ou_igual_12_semanas_na_primeira_consulta",    "MG_CON1_12SEM_MES",      NA,                   NA,
                         "smi_cpn_mulheres_gravidas_com_tratamento_sindromico_para_its",       "MG_ITS_DIAG_TX",      NA,                   NA,
             "smi_cpn_mulheres_gravidas_cuja_profilaxia_final_foi_biprofilaxia_nvp_azt",       "MG_HIV_POS_ARV",      NA,       "Biprofilaxia",
               "smi_cpn_mulheres_gravidas_cuja_profilaxia_final_foi_monoprofilaxia_nvp",       "MG_HIV_POS_ARV",      NA,     "Monoprofilaxia",
                                           "smi_cpn_mulheres_gravidas_em_ctz_a_entrada",           "MG_HIV_CTZ",      NA,      "CTZ a entrada",
                                          "smi_cpn_mulheres_gravidas_em_tarv_a_entrada",       "MG_HIV_POS_ARV",      NA,     "TARV a entrada",
                      "smi_cpn_mulheres_gravidas_que_iniciaram_tarv_durante_a_gravidez",       "MG_HIV_POS_ARV",      NA,        "Inicio TARV",
     "smi_cpn_mulheres_gravidas_que_iniciaram_e_ou_receberam_suplementos_nutricionaiss",        "MG_NUT_SUPLEM",      NA,                   NA,
                                  "smi_cpn_mulheres_gravidas_que_receberam_1a_dose_vat",            "MG_VAT_1D",      NA,                   NA,
                               "smi_cpn_mulheres_gravidas_que_receberam_2_doses_de_tip",      "MG_MAL_TIP_2DOS",      NA,                   NA,
                               "smi_cpn_mulheres_gravidas_que_receberam_2a_5a_dose_vat",          "MG_VAT_2_5D",      NA,                   NA,
             "smi_cpn_mulheres_gravidas_que_receberam_3a_dose_de_tratamento_de_sifilis",      "MG_ITS_SIF_3DOS",      NA,                   NA,
                       "smi_cpn_mulheres_gravidas_que_receberam_4_ou_mais_doses_de_tip",      "MG_MAL_TIP_4DOS",      NA,                   NA,
                                  "smi_cpn_mulheres_gravidas_que_receberam_misoprostol",   "MG_HPP_MISOPROSTOL",      NA,                   NA,
                      "smi_cpn_mulheres_gravidas_que_receberam_rede_mosquiteira_remtil",        "MG_MAL_REMTIL",      NA,                   NA,
  "smi_cpn_mulheres_gravidas_que_receberam_a_3a_dose_ou_mais_sal_ferroso_com_ac_folico",     "MG_NUT_SALFER_3D",      NA,                   NA,
                      "smi_cpn_mulheres_gravidas_que_receberam_tratamento_para_malaria",       "MG_MAL_DIAG_TX",      NA,                   NA,
                    "smi_cpn_mulheres_gravidas_que_tiveram_desnutricao_aguda_grave_dag",           "MG_NUT_DAG",      NA,                   NA,
                 "smi_cpn_mulheres_gravidas_que_tiveram_desnutricao_aguda_moderada_dam",           "MG_NUT_DAM",      NA,                   NA,
                       "smi_cpn_mulheres_gravidas_testadas_hiv_negativas_durante_a_cpn",        "MG_HIV_ESTADO",      NA,           "Negativo",
                       "smi_cpn_mulheres_gravidas_testadas_hiv_positivas_durante_a_cpn",        "MG_HIV_ESTADO",      NA,           "Positivo",
                            "smi_cpn_mulheres_gravidas_testadas_negativas_para_sifilis",   "MG_ITS_TESTADA_SIF",      NA,           "Negativo",
                            "smi_cpn_mulheres_gravidas_testadas_positivas_para_sifilis",   "MG_ITS_TESTADA_SIF",      NA,           "Positivo",
                                "smi_cpn_parceiros_que_receberam_tratamento_de_sifilis",      "PARCEIRO_SIF_TX",      NA,                   NA,
                                          "smi_cpn_parceiros_testados_negativos_na_cpn", "PARCEIRO_HIV_TESTADO",      NA,           "Negativo",
                                          "smi_cpn_parceiros_testados_positivos_na_cpn", "PARCEIRO_HIV_TESTADO",      NA,           "Positivo",
              "smi_cpn_total_de_mulheres_gravidas_inscritas_no_periodo_total_da_coorte",       "MG_CON1_COORTE",      NA,                   NA,
                                                 "smi_cpn_total_de_parceiros_presentes",    "PARCEIRO_PRESENTE",      NA,                   NA,
               "smi_cpn_mulheres_gravidas_que_fizeram_a_4_ou_mais_consultas_pre_natais",       "MG_CON4_COORTE",      NA,                   NA
  )

usethis::use_data(data_sisma_smi_cpn_map, overwrite = TRUE)


data_sisma_ats_results <-
tibble::tribble(
                                                                            ~indicator, ~indicator_new,        ~sex,    ~age, ~age_coarse,        ~modality, ~result_status,
           "mz_ats_resultado_por_grupo_etario_outro_atip_negativo_20_24_anos_feminino",      "ATS_TST",  "Feminino", "20-24",          NA, "ATS-ATIP Outro",     "Negativo",
           "mz_ats_resultado_por_grupo_etario_outro_atip_negativo_25_49_anos_feminino",      "ATS_TST",  "Feminino", "25-49",          NA, "ATS-ATIP Outro",     "Negativo",
          "mz_ats_resultado_por_grupo_etario_outro_atip_negativo_25_49_anos_masculino",      "ATS_TST", "Masculino", "25-49",          NA, "ATS-ATIP Outro",     "Negativo",
              "mz_ats_resultado_por_grupo_etario_outro_atip_negativo_50_anos_feminino",      "ATS_TST",  "Feminino",   "50+",          NA, "ATS-ATIP Outro",     "Negativo",
           "mz_ats_resultado_por_grupo_etario_outro_atip_positivo_20_24_anos_feminino",      "ATS_TST",  "Feminino", "20-24",          NA, "ATS-ATIP Outro",     "Positivo",
          "mz_ats_resultado_por_grupo_etario_outro_atip_positivo_20_24_anos_masculino",      "ATS_TST", "Masculino", "20-24",          NA, "ATS-ATIP Outro",     "Positivo",
           "mz_ats_resultado_por_grupo_etario_outro_atip_positivo_25_49_anos_feminino",      "ATS_TST",  "Feminino", "25-49",          NA, "ATS-ATIP Outro",     "Positivo",
          "mz_ats_resultado_por_grupo_etario_outro_atip_positivo_25_49_anos_masculino",      "ATS_TST", "Masculino", "25-49",          NA, "ATS-ATIP Outro",     "Positivo",
                    "mz_ats_resultado_por_grupo_etario_uats_negativo_50_anos_feminino",      "ATS_TST",  "Feminino",   "50+",          NA,       "ATS-UATS",     "Negativo",
                   "mz_ats_resultado_por_grupo_etario_uats_negativo_50_anos_masculino",      "ATS_TST", "Masculino",   "50+",          NA,       "ATS-UATS",     "Negativo",
              "mz_ats_resultado_por_grupo_etario_triagem_negativo_20_24_anos_feminino",      "ATS_TST",  "Feminino", "20-24",          NA,    "ATS-Triagem",     "Negativo",
             "mz_ats_resultado_por_grupo_etario_triagem_negativo_20_24_anos_masculino",      "ATS_TST", "Masculino", "20-24",          NA,    "ATS-Triagem",     "Negativo",
              "mz_ats_resultado_por_grupo_etario_triagem_negativo_25_49_anos_feminino",      "ATS_TST",  "Feminino", "25-49",          NA,    "ATS-Triagem",     "Negativo",
             "mz_ats_resultado_por_grupo_etario_triagem_negativo_25_49_anos_masculino",      "ATS_TST", "Masculino", "25-49",          NA,    "ATS-Triagem",     "Negativo",
                "mz_ats_resultado_por_grupo_etario_triagem_negativo_50_anos_masculino",      "ATS_TST", "Masculino",   "50+",          NA,    "ATS-Triagem",     "Negativo",
              "mz_ats_resultado_por_grupo_etario_triagem_positivo_25_49_anos_feminino",      "ATS_TST",  "Feminino", "25-49",          NA,    "ATS-Triagem",     "Positivo",
             "mz_ats_resultado_por_grupo_etario_triagem_positivo_25_49_anos_masculino",      "ATS_TST", "Masculino", "25-49",          NA,    "ATS-Triagem",     "Positivo",
                 "mz_ats_resultado_por_grupo_etario_triagem_positivo_50_anos_feminino",      "ATS_TST",  "Feminino",   "50+",          NA,    "ATS-Triagem",     "Positivo",
                "mz_ats_resultado_por_grupo_etario_triagem_positivo_50_anos_masculino",      "ATS_TST", "Masculino",   "50+",          NA,    "ATS-Triagem",     "Positivo",
                "mz_ats_resultado_por_grupo_etario_triagem_negativo_1_9_anos_feminino",      "ATS_TST",  "Feminino", "01-09",       "<15",    "ATS-Triagem",     "Negativo",
               "mz_ats_resultado_por_grupo_etario_triagem_negativo_1_9_anos_masculino",      "ATS_TST", "Masculino", "01-09",       "<15",    "ATS-Triagem",     "Negativo",
              "mz_ats_resultado_por_grupo_etario_triagem_negativo_10_14_anos_feminino",      "ATS_TST",  "Feminino", "10-14",       "<15",    "ATS-Triagem",     "Negativo",
             "mz_ats_resultado_por_grupo_etario_triagem_negativo_10_14_anos_masculino",      "ATS_TST", "Masculino", "10-14",       "<15",    "ATS-Triagem",     "Negativo",
              "mz_ats_resultado_por_grupo_etario_triagem_negativo_15_19_anos_feminino",      "ATS_TST",  "Feminino", "15-19",          NA,    "ATS-Triagem",     "Negativo",
             "mz_ats_resultado_por_grupo_etario_triagem_negativo_15_19_anos_masculino",      "ATS_TST", "Masculino", "15-19",          NA,    "ATS-Triagem",     "Negativo",
              "mz_ats_resultado_por_grupo_etario_triagem_positivo_10_14_anos_feminino",      "ATS_TST",  "Feminino", "10-14",       "<15",    "ATS-Triagem",     "Positivo",
                   "mz_ats_resultado_por_grupo_etario_triagem_negativo_1_ano_feminino",      "ATS_TST",  "Feminino",   "<01",       "<15",    "ATS-Triagem",     "Negativo",
                  "mz_ats_resultado_por_grupo_etario_triagem_negativo_1_ano_masculino",      "ATS_TST", "Masculino",   "<01",       "<15",    "ATS-Triagem",     "Negativo",
                 "mz_ats_resultado_por_grupo_etario_triagem_negativo_50_anos_feminino",      "ATS_TST",  "Feminino",   "50+",          NA,    "ATS-Triagem",     "Negativo",
                "mz_ats_resultado_por_grupo_etario_triagem_positivo_1_9_anos_feminino",      "ATS_TST",  "Feminino", "01-09",       "<15",    "ATS-Triagem",     "Positivo",
              "mz_ats_resultado_por_grupo_etario_triagem_positivo_20_24_anos_feminino",      "ATS_TST",  "Feminino", "20-24",          NA,    "ATS-Triagem",     "Positivo",
                   "mz_ats_resultado_por_grupo_etario_uats_negativo_1_9_anos_feminino",      "ATS_TST",  "Feminino", "01-09",       "<15",       "ATS-UATS",     "Negativo",
                  "mz_ats_resultado_por_grupo_etario_uats_negativo_1_9_anos_masculino",      "ATS_TST", "Masculino", "01-09",       "<15",       "ATS-UATS",     "Negativo",
                 "mz_ats_resultado_por_grupo_etario_uats_negativo_15_19_anos_feminino",      "ATS_TST",  "Feminino", "15-19",          NA,       "ATS-UATS",     "Negativo",
                "mz_ats_resultado_por_grupo_etario_uats_negativo_15_19_anos_masculino",      "ATS_TST", "Masculino", "15-19",          NA,       "ATS-UATS",     "Negativo",
                 "mz_ats_resultado_por_grupo_etario_uats_negativo_20_24_anos_feminino",      "ATS_TST",  "Feminino", "20-24",          NA,       "ATS-UATS",     "Negativo",
                "mz_ats_resultado_por_grupo_etario_uats_negativo_20_24_anos_masculino",      "ATS_TST", "Masculino", "20-24",          NA,       "ATS-UATS",     "Negativo",
                 "mz_ats_resultado_por_grupo_etario_uats_negativo_25_49_anos_feminino",      "ATS_TST",  "Feminino", "25-49",          NA,       "ATS-UATS",     "Negativo",
                "mz_ats_resultado_por_grupo_etario_uats_negativo_25_49_anos_masculino",      "ATS_TST", "Masculino", "25-49",          NA,       "ATS-UATS",     "Negativo",
                "mz_ats_resultado_por_grupo_etario_uats_positivo_15_19_anos_masculino",      "ATS_TST", "Masculino", "15-19",          NA,       "ATS-UATS",     "Positivo",
                "mz_ats_resultado_por_grupo_etario_uats_positivo_20_24_anos_masculino",      "ATS_TST", "Masculino", "20-24",          NA,       "ATS-UATS",     "Positivo",
                 "mz_ats_resultado_por_grupo_etario_uats_positivo_25_49_anos_feminino",      "ATS_TST",  "Feminino", "25-49",          NA,       "ATS-UATS",     "Positivo",
                "mz_ats_resultado_por_grupo_etario_uats_positivo_25_49_anos_masculino",      "ATS_TST", "Masculino", "25-49",          NA,       "ATS-UATS",     "Positivo",
                    "mz_ats_resultado_por_grupo_etario_uats_positivo_50_anos_feminino",      "ATS_TST",  "Feminino",   "50+",          NA,       "ATS-UATS",     "Positivo",
                   "mz_ats_resultado_por_grupo_etario_uats_positivo_50_anos_masculino",      "ATS_TST", "Masculino",   "50+",          NA,       "ATS-UATS",     "Positivo",
                "mz_ats_resultado_por_grupo_etario_ats_c_negativo_15_19_anos_feminino",      "ATS_TST",  "Feminino", "15-19",          NA,          "ATS-C",     "Negativo",
               "mz_ats_resultado_por_grupo_etario_ats_c_negativo_15_19_anos_masculino",      "ATS_TST", "Masculino", "15-19",          NA,          "ATS-C",     "Negativo",
                "mz_ats_resultado_por_grupo_etario_ats_c_negativo_20_24_anos_feminino",      "ATS_TST",  "Feminino", "20-24",          NA,          "ATS-C",     "Negativo",
               "mz_ats_resultado_por_grupo_etario_ats_c_negativo_20_24_anos_masculino",      "ATS_TST", "Masculino", "20-24",          NA,          "ATS-C",     "Negativo",
                "mz_ats_resultado_por_grupo_etario_ats_c_negativo_25_49_anos_feminino",      "ATS_TST",  "Feminino", "25-49",          NA,          "ATS-C",     "Negativo",
               "mz_ats_resultado_por_grupo_etario_ats_c_negativo_25_49_anos_masculino",      "ATS_TST", "Masculino", "25-49",          NA,          "ATS-C",     "Negativo",
                   "mz_ats_resultado_por_grupo_etario_ats_c_negativo_50_anos_feminino",      "ATS_TST",  "Feminino",   "50+",          NA,          "ATS-C",     "Negativo",
                  "mz_ats_resultado_por_grupo_etario_ats_c_negativo_50_anos_masculino",      "ATS_TST", "Masculino",   "50+",          NA,          "ATS-C",     "Negativo",
               "mz_ats_resultado_por_grupo_etario_ats_c_positivo_20_24_anos_masculino",      "ATS_TST", "Masculino", "20-24",          NA,          "ATS-C",     "Positivo",
                "mz_ats_resultado_por_grupo_etario_ats_c_positivo_25_49_anos_feminino",      "ATS_TST",  "Feminino", "25-49",          NA,          "ATS-C",     "Positivo",
                  "mz_ats_resultado_por_grupo_etario_ats_c_positivo_50_anos_masculino",      "ATS_TST", "Masculino",   "50+",          NA,          "ATS-C",     "Positivo",
   "mz_ats_resultado_por_grupo_etario_consultas_externas_negativo_15_19_anos_feminino",      "ATS_TST",  "Feminino", "15-19",          NA,         "ATS-CE",     "Negativo",
  "mz_ats_resultado_por_grupo_etario_consultas_externas_negativo_15_19_anos_masculino",      "ATS_TST", "Masculino", "15-19",          NA,         "ATS-CE",     "Negativo",
   "mz_ats_resultado_por_grupo_etario_consultas_externas_negativo_20_24_anos_feminino",      "ATS_TST",  "Feminino", "20-24",          NA,         "ATS-CE",     "Negativo",
  "mz_ats_resultado_por_grupo_etario_consultas_externas_negativo_20_24_anos_masculino",      "ATS_TST", "Masculino", "20-24",          NA,         "ATS-CE",     "Negativo",
   "mz_ats_resultado_por_grupo_etario_consultas_externas_negativo_25_49_anos_feminino",      "ATS_TST",  "Feminino", "25-49",          NA,         "ATS-CE",     "Negativo",
  "mz_ats_resultado_por_grupo_etario_consultas_externas_negativo_25_49_anos_masculino",      "ATS_TST", "Masculino", "25-49",          NA,         "ATS-CE",     "Negativo",
      "mz_ats_resultado_por_grupo_etario_consultas_externas_negativo_50_anos_feminino",      "ATS_TST",  "Feminino",   "50+",          NA,         "ATS-CE",     "Negativo",
     "mz_ats_resultado_por_grupo_etario_consultas_externas_negativo_50_anos_masculino",      "ATS_TST", "Masculino",   "50+",          NA,         "ATS-CE",     "Negativo",
   "mz_ats_resultado_por_grupo_etario_consultas_externas_positivo_25_49_anos_feminino",      "ATS_TST",  "Feminino", "25-49",          NA,         "ATS-CE",     "Positivo",
           "mz_ats_resultado_por_grupo_etario_outro_atip_negativo_15_19_anos_feminino",      "ATS_TST",  "Feminino", "15-19",          NA, "ATS-ATIP Outro",     "Negativo",
          "mz_ats_resultado_por_grupo_etario_outro_atip_negativo_15_19_anos_masculino",      "ATS_TST", "Masculino", "15-19",          NA, "ATS-ATIP Outro",     "Negativo",
          "mz_ats_resultado_por_grupo_etario_outro_atip_negativo_20_24_anos_masculino",      "ATS_TST", "Masculino", "20-24",          NA, "ATS-ATIP Outro",     "Negativo",
             "mz_ats_resultado_por_grupo_etario_outro_atip_negativo_50_anos_masculino",      "ATS_TST", "Masculino",   "50+",          NA, "ATS-ATIP Outro",     "Negativo",
                    "mz_ats_resultado_por_grupo_etario_smi_negativo_1_9_anos_feminino",      "ATS_TST",  "Feminino", "01-09",       "<15",        "ATS-SMI",     "Negativo",
                   "mz_ats_resultado_por_grupo_etario_smi_negativo_1_9_anos_masculino",      "ATS_TST", "Masculino", "01-09",       "<15",        "ATS-SMI",     "Negativo",
                  "mz_ats_resultado_por_grupo_etario_smi_negativo_10_14_anos_feminino",      "ATS_TST",  "Feminino", "10-14",       "<15",        "ATS-SMI",     "Negativo",
                 "mz_ats_resultado_por_grupo_etario_smi_negativo_10_14_anos_masculino",      "ATS_TST", "Masculino", "10-14",       "<15",        "ATS-SMI",     "Negativo",
                  "mz_ats_resultado_por_grupo_etario_smi_negativo_15_19_anos_feminino",      "ATS_TST",  "Feminino", "15-19",          NA,        "ATS-SMI",     "Negativo",
                  "mz_ats_resultado_por_grupo_etario_smi_negativo_20_24_anos_feminino",      "ATS_TST",  "Feminino", "20-24",          NA,        "ATS-SMI",     "Negativo",
                 "mz_ats_resultado_por_grupo_etario_smi_negativo_20_24_anos_masculino",      "ATS_TST", "Masculino", "20-24",          NA,        "ATS-SMI",     "Negativo",
                  "mz_ats_resultado_por_grupo_etario_smi_negativo_25_49_anos_feminino",      "ATS_TST",  "Feminino", "25-49",          NA,        "ATS-SMI",     "Negativo",
                 "mz_ats_resultado_por_grupo_etario_smi_negativo_25_49_anos_masculino",      "ATS_TST", "Masculino", "25-49",          NA,        "ATS-SMI",     "Negativo",
                     "mz_ats_resultado_por_grupo_etario_smi_negativo_50_anos_feminino",      "ATS_TST",  "Feminino",   "50+",          NA,        "ATS-SMI",     "Negativo",
                  "mz_ats_resultado_por_grupo_etario_smi_positivo_20_24_anos_feminino",      "ATS_TST",  "Feminino", "20-24",          NA,        "ATS-SMI",     "Positivo",
                     "mz_ats_resultado_por_grupo_etario_tb_negativo_1_9_anos_feminino",      "ATS_TST",  "Feminino", "01-09",       "<15",         "ATS-TB",     "Negativo",
                    "mz_ats_resultado_por_grupo_etario_tb_negativo_1_9_anos_masculino",      "ATS_TST", "Masculino", "01-09",       "<15",         "ATS-TB",     "Negativo",
                   "mz_ats_resultado_por_grupo_etario_tb_negativo_10_14_anos_feminino",      "ATS_TST",  "Feminino", "10-14",       "<15",         "ATS-TB",     "Negativo",
                  "mz_ats_resultado_por_grupo_etario_tb_negativo_10_14_anos_masculino",      "ATS_TST", "Masculino", "10-14",       "<15",         "ATS-TB",     "Negativo",
                   "mz_ats_resultado_por_grupo_etario_tb_negativo_20_24_anos_feminino",      "ATS_TST",  "Feminino", "20-24",          NA,         "ATS-TB",     "Negativo",
                  "mz_ats_resultado_por_grupo_etario_tb_negativo_20_24_anos_masculino",      "ATS_TST", "Masculino", "20-24",          NA,         "ATS-TB",     "Negativo",
                   "mz_ats_resultado_por_grupo_etario_tb_negativo_25_49_anos_feminino",      "ATS_TST",  "Feminino", "25-49",          NA,         "ATS-TB",     "Negativo",
                  "mz_ats_resultado_por_grupo_etario_tb_negativo_25_49_anos_masculino",      "ATS_TST", "Masculino", "25-49",          NA,         "ATS-TB",     "Negativo",
                      "mz_ats_resultado_por_grupo_etario_tb_negativo_50_anos_feminino",      "ATS_TST",  "Feminino",   "50+",          NA,         "ATS-TB",     "Negativo",
                     "mz_ats_resultado_por_grupo_etario_tb_negativo_50_anos_masculino",      "ATS_TST", "Masculino",   "50+",          NA,         "ATS-TB",     "Negativo",
                   "mz_ats_resultado_por_grupo_etario_tb_positivo_15_19_anos_feminino",      "ATS_TST",  "Feminino", "15-19",          NA,         "ATS-TB",     "Positivo",
                   "mz_ats_resultado_por_grupo_etario_tb_positivo_25_49_anos_feminino",      "ATS_TST",  "Feminino", "25-49",          NA,         "ATS-TB",     "Positivo",
                  "mz_ats_resultado_por_grupo_etario_tb_positivo_25_49_anos_masculino",      "ATS_TST", "Masculino", "25-49",          NA,         "ATS-TB",     "Positivo",
              "mz_ats_resultado_por_grupo_etario_triagem_positivo_15_19_anos_feminino",      "ATS_TST",  "Feminino", "15-19",          NA,    "ATS-Triagem",     "Positivo",
                 "mz_ats_resultado_por_grupo_etario_uats_negativo_10_14_anos_feminino",      "ATS_TST",  "Feminino", "10-14",       "<15",       "ATS-UATS",     "Negativo",
                "mz_ats_resultado_por_grupo_etario_uats_negativo_10_14_anos_masculino",      "ATS_TST", "Masculino", "10-14",       "<15",       "ATS-UATS",     "Negativo",
                 "mz_ats_resultado_por_grupo_etario_uats_positivo_10_14_anos_feminino",      "ATS_TST",  "Feminino", "10-14",       "<15",       "ATS-UATS",     "Positivo",
                "mz_ats_resultado_por_grupo_etario_ats_c_positivo_10_14_anos_feminino",      "ATS_TST",  "Feminino", "10-14",       "<15",          "ATS-C",     "Positivo",
      "mz_ats_resultado_por_grupo_etario_banco_de_socorros_negativo_1_9_anos_feminino",      "ATS_TST",  "Feminino", "01-09",       "<15",        "ATS-BdS",     "Negativo",
     "mz_ats_resultado_por_grupo_etario_banco_de_socorros_negativo_1_9_anos_masculino",      "ATS_TST", "Masculino", "01-09",       "<15",        "ATS-BdS",     "Negativo",
    "mz_ats_resultado_por_grupo_etario_banco_de_socorros_negativo_10_14_anos_feminino",      "ATS_TST",  "Feminino", "10-14",       "<15",        "ATS-BdS",     "Negativo",
   "mz_ats_resultado_por_grupo_etario_banco_de_socorros_negativo_10_14_anos_masculino",      "ATS_TST", "Masculino", "10-14",       "<15",        "ATS-BdS",     "Negativo",
    "mz_ats_resultado_por_grupo_etario_banco_de_socorros_negativo_15_19_anos_feminino",      "ATS_TST",  "Feminino", "15-19",          NA,        "ATS-BdS",     "Negativo",
   "mz_ats_resultado_por_grupo_etario_banco_de_socorros_negativo_15_19_anos_masculino",      "ATS_TST", "Masculino", "15-19",          NA,        "ATS-BdS",     "Negativo",
    "mz_ats_resultado_por_grupo_etario_banco_de_socorros_negativo_20_24_anos_feminino",      "ATS_TST",  "Feminino", "20-24",          NA,        "ATS-BdS",     "Negativo",
   "mz_ats_resultado_por_grupo_etario_banco_de_socorros_negativo_20_24_anos_masculino",      "ATS_TST", "Masculino", "20-24",          NA,        "ATS-BdS",     "Negativo",
    "mz_ats_resultado_por_grupo_etario_banco_de_socorros_negativo_25_49_anos_feminino",      "ATS_TST",  "Feminino", "25-49",          NA,        "ATS-BdS",     "Negativo",
   "mz_ats_resultado_por_grupo_etario_banco_de_socorros_negativo_25_49_anos_masculino",      "ATS_TST", "Masculino", "25-49",          NA,        "ATS-BdS",     "Negativo",
       "mz_ats_resultado_por_grupo_etario_banco_de_socorros_negativo_50_anos_feminino",      "ATS_TST",  "Feminino",   "50+",          NA,        "ATS-BdS",     "Negativo",
      "mz_ats_resultado_por_grupo_etario_banco_de_socorros_negativo_50_anos_masculino",      "ATS_TST", "Masculino",   "50+",          NA,        "ATS-BdS",     "Negativo",
    "mz_ats_resultado_por_grupo_etario_banco_de_socorros_positivo_20_24_anos_feminino",      "ATS_TST",  "Feminino", "20-24",          NA,        "ATS-BdS",     "Positivo",
    "mz_ats_resultado_por_grupo_etario_banco_de_socorros_positivo_25_49_anos_feminino",      "ATS_TST",  "Feminino", "25-49",          NA,        "ATS-BdS",     "Positivo",
   "mz_ats_resultado_por_grupo_etario_banco_de_socorros_positivo_25_49_anos_masculino",      "ATS_TST", "Masculino", "25-49",          NA,        "ATS-BdS",     "Positivo",
     "mz_ats_resultado_por_grupo_etario_consultas_externas_negativo_1_9_anos_feminino",      "ATS_TST",  "Feminino", "01-09",       "<15",         "ATS-CE",     "Negativo",
    "mz_ats_resultado_por_grupo_etario_consultas_externas_negativo_1_9_anos_masculino",      "ATS_TST", "Masculino", "01-09",       "<15",         "ATS-CE",     "Negativo",
   "mz_ats_resultado_por_grupo_etario_consultas_externas_negativo_10_14_anos_feminino",      "ATS_TST",  "Feminino", "10-14",       "<15",         "ATS-CE",     "Negativo",
  "mz_ats_resultado_por_grupo_etario_consultas_externas_negativo_10_14_anos_masculino",      "ATS_TST", "Masculino", "10-14",       "<15",         "ATS-CE",     "Negativo",
   "mz_ats_resultado_por_grupo_etario_consultas_externas_positivo_20_24_anos_feminino",      "ATS_TST",  "Feminino", "20-24",          NA,         "ATS-CE",     "Positivo",
  "mz_ats_resultado_por_grupo_etario_consultas_externas_positivo_25_49_anos_masculino",      "ATS_TST", "Masculino", "25-49",          NA,         "ATS-CE",     "Positivo",
                    "mz_ats_resultado_por_grupo_etario_smi_positivo_1_9_anos_feminino",      "ATS_TST",  "Feminino", "01-09",       "<15",        "ATS-SMI",     "Positivo",
                  "mz_ats_resultado_por_grupo_etario_smi_positivo_15_19_anos_feminino",      "ATS_TST",  "Feminino", "15-19",          NA,        "ATS-SMI",     "Positivo",
             "mz_ats_resultado_por_grupo_etario_triagem_positivo_20_24_anos_masculino",      "ATS_TST", "Masculino", "20-24",          NA,    "ATS-Triagem",     "Positivo",
                 "mz_ats_resultado_por_grupo_etario_uats_positivo_20_24_anos_feminino",      "ATS_TST",  "Feminino", "20-24",          NA,       "ATS-UATS",     "Positivo",
                  "mz_ats_resultado_por_grupo_etario_ats_c_negativo_1_9_anos_feminino",      "ATS_TST",  "Feminino", "01-09",       "<15",          "ATS-C",     "Negativo",
                 "mz_ats_resultado_por_grupo_etario_ats_c_negativo_1_9_anos_masculino",      "ATS_TST", "Masculino", "01-09",       "<15",          "ATS-C",     "Negativo",
                "mz_ats_resultado_por_grupo_etario_ats_c_negativo_10_14_anos_feminino",      "ATS_TST",  "Feminino", "10-14",       "<15",          "ATS-C",     "Negativo",
               "mz_ats_resultado_por_grupo_etario_ats_c_negativo_10_14_anos_masculino",      "ATS_TST", "Masculino", "10-14",       "<15",          "ATS-C",     "Negativo",
                "mz_ats_resultado_por_grupo_etario_ats_c_positivo_20_24_anos_feminino",      "ATS_TST",  "Feminino", "20-24",          NA,          "ATS-C",     "Positivo",
               "mz_ats_resultado_por_grupo_etario_ats_c_positivo_25_49_anos_masculino",      "ATS_TST", "Masculino", "25-49",          NA,          "ATS-C",     "Positivo",
       "mz_ats_resultado_por_grupo_etario_banco_de_socorros_positivo_50_anos_feminino",      "ATS_TST",  "Feminino",   "50+",          NA,        "ATS-BdS",     "Positivo",
      "mz_ats_resultado_por_grupo_etario_banco_de_socorros_positivo_50_anos_masculino",      "ATS_TST", "Masculino",   "50+",          NA,        "ATS-BdS",     "Positivo",
                 "mz_ats_resultado_por_grupo_etario_smi_positivo_15_19_anos_masculino",      "ATS_TST", "Masculino", "15-19",          NA,        "ATS-SMI",     "Positivo",
                 "mz_ats_resultado_por_grupo_etario_smi_positivo_25_49_anos_masculino",      "ATS_TST", "Masculino", "25-49",          NA,        "ATS-SMI",     "Positivo",
                    "mz_ats_resultado_por_grupo_etario_smi_positivo_50_anos_masculino",      "ATS_TST", "Masculino",   "50+",          NA,        "ATS-SMI",     "Positivo",
                   "mz_ats_resultado_por_grupo_etario_tb_negativo_15_19_anos_feminino",      "ATS_TST",  "Feminino", "15-19",          NA,         "ATS-TB",     "Negativo",
                  "mz_ats_resultado_por_grupo_etario_tb_negativo_15_19_anos_masculino",      "ATS_TST", "Masculino", "15-19",          NA,         "ATS-TB",     "Negativo",
                   "mz_ats_resultado_por_grupo_etario_tb_positivo_20_24_anos_feminino",      "ATS_TST",  "Feminino", "20-24",          NA,         "ATS-TB",     "Positivo",
                   "mz_ats_resultado_por_grupo_etario_uats_positivo_1_9_anos_feminino",      "ATS_TST",  "Feminino", "01-09",       "<15",       "ATS-UATS",     "Positivo",
                  "mz_ats_resultado_por_grupo_etario_uats_positivo_1_9_anos_masculino",      "ATS_TST", "Masculino", "01-09",       "<15",       "ATS-UATS",     "Positivo",
                 "mz_ats_resultado_por_grupo_etario_uats_positivo_15_19_anos_feminino",      "ATS_TST",  "Feminino", "15-19",          NA,       "ATS-UATS",     "Positivo",
                "mz_ats_resultado_por_grupo_etario_ats_c_positivo_15_19_anos_feminino",      "ATS_TST",  "Feminino", "15-19",          NA,          "ATS-C",     "Positivo",
         "mz_ats_resultado_por_grupo_etario_banco_de_socorros_negativo_1_ano_feminino",      "ATS_TST",  "Feminino",   "<01",       "<15",        "ATS-BdS",     "Negativo",
   "mz_ats_resultado_por_grupo_etario_banco_de_socorros_positivo_20_24_anos_masculino",      "ATS_TST", "Masculino", "20-24",          NA,        "ATS-BdS",     "Positivo",
             "mz_ats_resultado_por_grupo_etario_outro_atip_negativo_1_9_anos_feminino",      "ATS_TST",  "Feminino", "01-09",       "<15", "ATS-ATIP Outro",     "Negativo",
           "mz_ats_resultado_por_grupo_etario_outro_atip_negativo_10_14_anos_feminino",      "ATS_TST",  "Feminino", "10-14",       "<15", "ATS-ATIP Outro",     "Negativo",
          "mz_ats_resultado_por_grupo_etario_outro_atip_negativo_10_14_anos_masculino",      "ATS_TST", "Masculino", "10-14",       "<15", "ATS-ATIP Outro",     "Negativo",
                   "mz_ats_resultado_por_grupo_etario_ats_c_positivo_50_anos_feminino",      "ATS_TST",  "Feminino",   "50+",          NA,          "ATS-C",     "Positivo",
                     "mz_ats_resultado_por_grupo_etario_uats_negativo_1_ano_masculino",      "ATS_TST", "Masculino",   "<01",       "<15",       "ATS-UATS",     "Negativo",
            "mz_ats_resultado_por_grupo_etario_outro_atip_negativo_1_9_anos_masculino",      "ATS_TST", "Masculino", "01-09",       "<15", "ATS-ATIP Outro",     "Negativo",
                 "mz_ats_resultado_por_grupo_etario_smi_negativo_15_19_anos_masculino",      "ATS_TST", "Masculino", "15-19",          NA,        "ATS-SMI",     "Negativo",
                  "mz_ats_resultado_por_grupo_etario_ats_c_positivo_1_9_anos_feminino",      "ATS_TST",  "Feminino", "01-09",       "<15",          "ATS-C",     "Positivo",
    "mz_ats_resultado_por_grupo_etario_banco_de_socorros_positivo_15_19_anos_feminino",      "ATS_TST",  "Feminino", "15-19",          NA,        "ATS-BdS",     "Positivo",
             "mz_ats_resultado_por_grupo_etario_triagem_positivo_10_14_anos_masculino",      "ATS_TST", "Masculino", "10-14",       "<15",    "ATS-Triagem",     "Positivo",
                    "mz_ats_resultado_por_grupo_etario_smi_negativo_50_anos_masculino",      "ATS_TST", "Masculino",   "50+",          NA,        "ATS-SMI",     "Negativo",
                       "mz_ats_resultado_por_grupo_etario_smi_negativo_1_ano_feminino",      "ATS_TST",  "Feminino",   "<01",       "<15",        "ATS-SMI",     "Negativo",
                  "mz_ats_resultado_por_grupo_etario_smi_positivo_25_49_anos_feminino",      "ATS_TST",  "Feminino", "25-49",          NA,        "ATS-SMI",     "Positivo",
               "mz_ats_resultado_por_grupo_etario_triagem_positivo_1_9_anos_masculino",      "ATS_TST", "Masculino", "01-09",       "<15",    "ATS-Triagem",     "Positivo",
                     "mz_ats_resultado_por_grupo_etario_ats_c_negativo_1_ano_feminino",      "ATS_TST",  "Feminino",   "<01",       "<15",          "ATS-C",     "Negativo",
                     "mz_ats_resultado_por_grupo_etario_smi_positivo_50_anos_feminino",      "ATS_TST",  "Feminino",   "50+",          NA,        "ATS-SMI",     "Positivo",
                    "mz_ats_resultado_por_grupo_etario_ats_c_negativo_1_ano_masculino",      "ATS_TST", "Masculino",   "<01",       "<15",          "ATS-C",     "Negativo",
               "mz_ats_resultado_por_grupo_etario_ats_c_positivo_15_19_anos_masculino",      "ATS_TST", "Masculino", "15-19",          NA,          "ATS-C",     "Positivo",
        "mz_ats_resultado_por_grupo_etario_consultas_externas_negativo_1_ano_feminino",      "ATS_TST",  "Feminino",   "<01",       "<15",         "ATS-CE",     "Negativo",
       "mz_ats_resultado_por_grupo_etario_consultas_externas_negativo_1_ano_masculino",      "ATS_TST", "Masculino",   "<01",       "<15",         "ATS-CE",     "Negativo",
                      "mz_ats_resultado_por_grupo_etario_smi_negativo_1_ano_masculino",      "ATS_TST", "Masculino",   "<01",       "<15",        "ATS-SMI",     "Negativo",
                      "mz_ats_resultado_por_grupo_etario_uats_negativo_1_ano_feminino",      "ATS_TST",  "Feminino",   "<01",       "<15",       "ATS-UATS",     "Negativo",
                "mz_ats_resultado_por_grupo_etario_outro_atip_negativo_1_ano_feminino",      "ATS_TST",  "Feminino",   "<01",       "<15", "ATS-ATIP Outro",     "Negativo",
               "mz_ats_resultado_por_grupo_etario_outro_atip_negativo_1_ano_masculino",      "ATS_TST", "Masculino",   "<01",       "<15", "ATS-ATIP Outro",     "Negativo",
             "mz_ats_resultado_por_grupo_etario_outro_atip_positivo_1_9_anos_feminino",      "ATS_TST",  "Feminino", "01-09",       "<15", "ATS-ATIP Outro",     "Positivo",
            "mz_ats_resultado_por_grupo_etario_outro_atip_positivo_1_9_anos_masculino",      "ATS_TST", "Masculino", "01-09",       "<15", "ATS-ATIP Outro",     "Positivo",
          "mz_ats_resultado_por_grupo_etario_outro_atip_positivo_10_14_anos_masculino",      "ATS_TST", "Masculino", "10-14",       "<15", "ATS-ATIP Outro",     "Positivo",
                  "mz_ats_resultado_por_grupo_etario_tb_positivo_20_24_anos_masculino",      "ATS_TST", "Masculino", "20-24",          NA,         "ATS-TB",     "Positivo",
                      "mz_ats_resultado_por_grupo_etario_tb_positivo_50_anos_feminino",      "ATS_TST",  "Feminino",   "50+",          NA,         "ATS-TB",     "Positivo",
                     "mz_ats_resultado_por_grupo_etario_tb_positivo_50_anos_masculino",      "ATS_TST", "Masculino",   "50+",          NA,         "ATS-TB",     "Positivo",
              "mz_ats_resultado_por_grupo_etario_outro_atip_positivo_50_anos_feminino",      "ATS_TST",  "Feminino",   "50+",          NA, "ATS-ATIP Outro",     "Positivo",
             "mz_ats_resultado_por_grupo_etario_triagem_positivo_15_19_anos_masculino",      "ATS_TST", "Masculino", "15-19",          NA,    "ATS-Triagem",     "Positivo",
  "mz_ats_resultado_por_grupo_etario_consultas_externas_positivo_20_24_anos_masculino",      "ATS_TST", "Masculino", "20-24",          NA,         "ATS-CE",     "Positivo",
             "mz_ats_resultado_por_grupo_etario_enfermaria_negativo_1_9_anos_feminino",      "ATS_TST",  "Feminino", "01-09",       "<15",        "ATS-Enf",     "Negativo",
            "mz_ats_resultado_por_grupo_etario_enfermaria_negativo_1_9_anos_masculino",      "ATS_TST", "Masculino", "01-09",       "<15",        "ATS-Enf",     "Negativo",
           "mz_ats_resultado_por_grupo_etario_enfermaria_negativo_10_14_anos_feminino",      "ATS_TST",  "Feminino", "10-14",       "<15",        "ATS-Enf",     "Negativo",
           "mz_ats_resultado_por_grupo_etario_enfermaria_negativo_15_19_anos_feminino",      "ATS_TST",  "Feminino", "15-19",          NA,        "ATS-Enf",     "Negativo",
           "mz_ats_resultado_por_grupo_etario_enfermaria_negativo_20_24_anos_feminino",      "ATS_TST",  "Feminino", "20-24",          NA,        "ATS-Enf",     "Negativo",
          "mz_ats_resultado_por_grupo_etario_enfermaria_negativo_20_24_anos_masculino",      "ATS_TST", "Masculino", "20-24",          NA,        "ATS-Enf",     "Negativo",
           "mz_ats_resultado_por_grupo_etario_enfermaria_negativo_25_49_anos_feminino",      "ATS_TST",  "Feminino", "25-49",          NA,        "ATS-Enf",     "Negativo",
          "mz_ats_resultado_por_grupo_etario_enfermaria_negativo_25_49_anos_masculino",      "ATS_TST", "Masculino", "25-49",          NA,        "ATS-Enf",     "Negativo",
              "mz_ats_resultado_por_grupo_etario_enfermaria_negativo_50_anos_feminino",      "ATS_TST",  "Feminino",   "50+",          NA,        "ATS-Enf",     "Negativo",
             "mz_ats_resultado_por_grupo_etario_enfermaria_negativo_50_anos_masculino",      "ATS_TST", "Masculino",   "50+",          NA,        "ATS-Enf",     "Negativo",
      "mz_ats_resultado_por_grupo_etario_consultas_externas_positivo_50_anos_feminino",      "ATS_TST",  "Feminino",   "50+",          NA,         "ATS-CE",     "Positivo",
           "mz_ats_resultado_por_grupo_etario_outro_atip_positivo_15_19_anos_feminino",      "ATS_TST",  "Feminino", "15-19",          NA, "ATS-ATIP Outro",     "Positivo",
                 "mz_ats_resultado_por_grupo_etario_ats_c_positivo_1_9_anos_masculino",      "ATS_TST", "Masculino", "01-09",       "<15",          "ATS-C",     "Positivo",
          "mz_ats_resultado_por_grupo_etario_enfermaria_positivo_25_49_anos_masculino",      "ATS_TST", "Masculino", "25-49",          NA,        "ATS-Enf",     "Positivo",
          "mz_ats_resultado_por_grupo_etario_outro_atip_positivo_15_19_anos_masculino",      "ATS_TST", "Masculino", "15-19",          NA, "ATS-ATIP Outro",     "Positivo",
                "mz_ats_resultado_por_grupo_etario_outro_atip_positivo_1_ano_feminino",      "ATS_TST",  "Feminino",   "<01",       "<15", "ATS-ATIP Outro",     "Positivo",
          "mz_ats_resultado_por_grupo_etario_enfermaria_negativo_10_14_anos_masculino",      "ATS_TST", "Masculino", "10-14",       "<15",        "ATS-Enf",     "Negativo",
          "mz_ats_resultado_por_grupo_etario_enfermaria_negativo_15_19_anos_masculino",      "ATS_TST", "Masculino", "15-19",          NA,        "ATS-Enf",     "Negativo",
           "mz_ats_resultado_por_grupo_etario_enfermaria_positivo_25_49_anos_feminino",      "ATS_TST",  "Feminino", "25-49",          NA,        "ATS-Enf",     "Positivo",
               "mz_ats_resultado_por_grupo_etario_ats_c_positivo_10_14_anos_masculino",      "ATS_TST", "Masculino", "10-14",       "<15",          "ATS-C",     "Positivo",
     "mz_ats_resultado_por_grupo_etario_consultas_externas_positivo_50_anos_masculino",      "ATS_TST", "Masculino",   "50+",          NA,         "ATS-CE",     "Positivo",
                    "mz_ats_resultado_por_grupo_etario_ats_c_positivo_1_ano_masculino",      "ATS_TST", "Masculino",   "<01",       "<15",          "ATS-C",     "Positivo",
                   "mz_ats_resultado_por_grupo_etario_smi_positivo_1_9_anos_masculino",      "ATS_TST", "Masculino", "01-09",       "<15",        "ATS-SMI",     "Positivo",
   "mz_ats_resultado_por_grupo_etario_banco_de_socorros_positivo_15_19_anos_masculino",      "ATS_TST", "Masculino", "15-19",          NA,        "ATS-BdS",     "Positivo",
                "mz_ats_resultado_por_grupo_etario_enfermaria_negativo_1_ano_feminino",      "ATS_TST",  "Feminino",   "<01",       "<15",        "ATS-Enf",     "Negativo",
                        "mz_ats_resultado_por_grupo_etario_tb_negativo_1_ano_feminino",      "ATS_TST",  "Feminino",   "<01",       "<15",         "ATS-TB",     "Negativo",
               "mz_ats_resultado_por_grupo_etario_enfermaria_negativo_1_ano_masculino",      "ATS_TST", "Masculino",   "<01",       "<15",        "ATS-Enf",     "Negativo",
                  "mz_ats_resultado_por_grupo_etario_triagem_positivo_1_ano_masculino",      "ATS_TST", "Masculino",   "<01",       "<15",    "ATS-Triagem",     "Positivo",
    "mz_ats_resultado_por_grupo_etario_consultas_externas_positivo_1_9_anos_masculino",      "ATS_TST", "Masculino", "01-09",       "<15",         "ATS-CE",     "Positivo",
                      "mz_ats_resultado_por_grupo_etario_uats_positivo_1_ano_feminino",      "ATS_TST",  "Feminino",   "<01",       "<15",       "ATS-UATS",     "Positivo",
   "mz_ats_resultado_por_grupo_etario_consultas_externas_positivo_15_19_anos_feminino",      "ATS_TST",  "Feminino", "15-19",          NA,         "ATS-CE",     "Positivo",
                     "mz_ats_resultado_por_grupo_etario_tb_positivo_1_9_anos_feminino",      "ATS_TST",  "Feminino", "01-09",       "<15",         "ATS-TB",     "Positivo",
             "mz_ats_resultado_por_grupo_etario_outro_atip_positivo_50_anos_masculino",      "ATS_TST", "Masculino",   "50+",          NA, "ATS-ATIP Outro",     "Positivo",
  "mz_ats_resultado_por_grupo_etario_consultas_externas_positivo_15_19_anos_masculino",      "ATS_TST", "Masculino", "15-19",          NA,         "ATS-CE",     "Positivo",
                     "mz_ats_resultado_por_grupo_etario_uats_positivo_1_ano_masculino",      "ATS_TST", "Masculino",   "<01",       "<15",       "ATS-UATS",     "Positivo",
                "mz_ats_resultado_por_grupo_etario_uats_positivo_10_14_anos_masculino",      "ATS_TST", "Masculino", "10-14",       "<15",       "ATS-UATS",     "Positivo",
           "mz_ats_resultado_por_grupo_etario_enfermaria_positivo_20_24_anos_feminino",      "ATS_TST",  "Feminino", "20-24",          NA,        "ATS-Enf",     "Positivo",
             "mz_ats_resultado_por_grupo_etario_enfermaria_positivo_50_anos_masculino",      "ATS_TST", "Masculino",   "50+",          NA,        "ATS-Enf",     "Positivo",
     "mz_ats_resultado_por_grupo_etario_consultas_externas_positivo_1_9_anos_feminino",      "ATS_TST",  "Feminino", "01-09",       "<15",         "ATS-CE",     "Positivo",
                   "mz_ats_resultado_por_grupo_etario_triagem_positivo_1_ano_feminino",      "ATS_TST",  "Feminino",   "<01",       "<15",    "ATS-Triagem",     "Positivo",
                     "mz_ats_resultado_por_grupo_etario_ats_c_positivo_1_ano_feminino",      "ATS_TST",  "Feminino",   "<01",       "<15",          "ATS-C",     "Positivo",
                   "mz_ats_resultado_por_grupo_etario_tb_positivo_10_14_anos_feminino",      "ATS_TST",  "Feminino", "10-14",       "<15",         "ATS-TB",     "Positivo",
                 "mz_ats_resultado_por_grupo_etario_smi_positivo_20_24_anos_masculino",      "ATS_TST", "Masculino", "20-24",          NA,        "ATS-SMI",     "Positivo",
        "mz_ats_resultado_por_grupo_etario_banco_de_socorros_negativo_1_ano_masculino",      "ATS_TST", "Masculino",   "<01",       "<15",        "ATS-BdS",     "Negativo",
  "mz_ats_resultado_por_grupo_etario_consultas_externas_positivo_10_14_anos_masculino",      "ATS_TST", "Masculino", "10-14",       "<15",         "ATS-CE",     "Positivo",
   "mz_ats_resultado_por_grupo_etario_banco_de_socorros_positivo_10_14_anos_masculino",      "ATS_TST", "Masculino", "10-14",       "<15",        "ATS-BdS",     "Positivo",
                  "mz_ats_resultado_por_grupo_etario_smi_positivo_10_14_anos_feminino",      "ATS_TST",  "Feminino", "10-14",       "<15",        "ATS-SMI",     "Positivo",
                 "mz_ats_resultado_por_grupo_etario_smi_positivo_10_14_anos_masculino",      "ATS_TST", "Masculino", "10-14",       "<15",        "ATS-SMI",     "Positivo",
     "mz_ats_resultado_por_grupo_etario_banco_de_socorros_positivo_1_9_anos_masculino",      "ATS_TST", "Masculino", "01-09",       "<15",        "ATS-BdS",     "Positivo",
          "mz_ats_resultado_por_grupo_etario_enfermaria_positivo_15_19_anos_masculino",      "ATS_TST", "Masculino", "15-19",          NA,        "ATS-Enf",     "Positivo",
        "mz_ats_resultado_por_grupo_etario_banco_de_socorros_positivo_1_ano_masculino",      "ATS_TST", "Masculino",   "<01",       "<15",        "ATS-BdS",     "Positivo",
                    "mz_ats_resultado_por_grupo_etario_tb_positivo_1_9_anos_masculino",      "ATS_TST", "Masculino", "01-09",       "<15",         "ATS-TB",     "Positivo",
       "mz_ats_resultado_por_grupo_etario_consultas_externas_positivo_1_ano_masculino",      "ATS_TST", "Masculino",   "<01",       "<15",         "ATS-CE",     "Positivo",
             "mz_ats_resultado_por_grupo_etario_enfermaria_positivo_1_9_anos_feminino",      "ATS_TST",  "Feminino", "01-09",       "<15",        "ATS-Enf",     "Positivo",
            "mz_ats_resultado_por_grupo_etario_enfermaria_positivo_1_9_anos_masculino",      "ATS_TST", "Masculino", "01-09",       "<15",        "ATS-Enf",     "Positivo",
      "mz_ats_resultado_por_grupo_etario_banco_de_socorros_positivo_1_9_anos_feminino",      "ATS_TST",  "Feminino", "01-09",       "<15",        "ATS-BdS",     "Positivo",
                       "mz_ats_resultado_por_grupo_etario_tb_negativo_1_anodata:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAWElEQVR42mNgGPTAxsZmJsVqQApgmGw1yApwKcQiT7phRBuCzzCSDSHGMKINIeDNmWQlA2IigKJwIssQkHdINgxfmBBtGDEBS3KCxBc7pMQgMYE5c/AXPwAwSX4lV3pTWwAAAABJRU5ErkJggg==_masculino",      "ATS_TST", "Masculino",   "<01",       "<15",         "ATS-TB",     "Negativo",
               "mz_ats_resultado_por_grupo_etario_enfermaria_positivo_1_ano_masculino",      "ATS_TST", "Masculino",   "<01",       "<15",        "ATS-Enf",     "Positivo",
           "mz_ats_resultado_por_grupo_etario_enfermaria_positivo_10_14_anos_feminino",      "ATS_TST",  "Feminino", "10-14",       "<15",        "ATS-Enf",     "Positivo",
           "mz_ats_resultado_por_grupo_etario_outro_atip_positivo_10_14_anos_feminino",      "ATS_TST",  "Feminino", "10-14",       "<15", "ATS-ATIP Outro",     "Positivo",
               "mz_ats_resultado_por_grupo_etario_outro_atip_positivo_1_ano_masculino",      "ATS_TST", "Masculino",   "<01",       "<15", "ATS-ATIP Outro",     "Positivo",
           "mz_ats_resultado_por_grupo_etario_enfermaria_positivo_15_19_anos_feminino",      "ATS_TST",  "Feminino", "15-19",          NA,        "ATS-Enf",     "Positivo",
              "mz_ats_resultado_por_grupo_etario_enfermaria_positivo_50_anos_feminino",      "ATS_TST",  "Feminino",   "50+",          NA,        "ATS-Enf",     "Positivo",
                "mz_ats_resultado_por_grupo_etario_enfermaria_positivo_1_ano_feminino",      "ATS_TST",  "Feminino",   "<01",       "<15",        "ATS-Enf",     "Positivo",
          "mz_ats_resultado_por_grupo_etario_enfermaria_positivo_20_24_anos_masculino",      "ATS_TST", "Masculino", "20-24",          NA,        "ATS-Enf",     "Positivo",
   "mz_ats_resultado_por_grupo_etario_consultas_externas_positivo_10_14_anos_feminino",      "ATS_TST",  "Feminino", "10-14",       "<15",         "ATS-CE",     "Positivo",
        "mz_ats_resultado_por_grupo_etario_consultas_externas_positivo_1_ano_feminino",      "ATS_TST",  "Feminino",   "<01",       "<15",         "ATS-CE",     "Positivo",
    "mz_ats_resultado_por_grupo_etario_banco_de_socorros_positivo_10_14_anos_feminino",      "ATS_TST",  "Feminino", "10-14",       "<15",        "ATS-BdS",     "Positivo",
                  "mz_ats_resultado_por_grupo_etario_tb_positivo_10_14_anos_masculino",      "ATS_TST", "Masculino", "10-14",       "<15",         "ATS-TB",     "Positivo",
                       "mz_ats_resultado_por_grupo_etario_tb_positivo_1_ano_masculino",      "ATS_TST", "Masculino",   "<01",       "<15",         "ATS-TB",     "Positivo",
                      "mz_ats_resultado_por_grupo_etario_smi_positivo_1_ano_masculino",      "ATS_TST", "Masculino",   "<01",       "<15",        "ATS-SMI",     "Positivo",
                       "mz_ats_resultado_por_grupo_etario_smi_positivo_1_ano_feminino",      "ATS_TST",  "Feminino",   "<01",       "<15",        "ATS-SMI",     "Positivo",
          "mz_ats_resultado_por_grupo_etario_enfermaria_positivo_10_14_anos_masculino",      "ATS_TST", "Masculino", "10-14",       "<15",        "ATS-Enf",     "Positivo",
         "mz_ats_resultado_por_grupo_etario_banco_de_socorros_positivo_1_ano_feminino",      "ATS_TST",  "Feminino",   "<01",       "<15",        "ATS-BdS",     "Positivo",
                  "mz_ats_resultado_por_grupo_etario_tb_positivo_15_19_anos_masculino",      "ATS_TST", "Masculino", "15-19",          NA,         "ATS-TB",     "Positivo",
                        "mz_ats_resultado_por_grupo_etario_tb_positivo_1_ano_feminino",      "ATS_TST",  "Feminino",   "<01",       "<15",         "ATS-TB",     "Positivo"
  )

usethis::use_data(data_sisma_ats_results, overwrite = TRUE)
